# write a program that does the following:
#  Create a hash.
#   - Add one key-value pair in the hash. The key should be :random_numbers. The value should be an array of five randomly generated integers between 12 and 21,
#    both inclusive.
#   - Create another key-value pair in the hash. The key should be :user_input. The value should be an array of five positive integers that the program receives
#    as user input, also in the range of 12 and 21, both inclusive.
# Do the following: leveraging the information in the hash.
#   - Ask the user to supply three numbers.
#   - For each number entered by the user, share the count of times the number was generated by the program.
#   - For each number entered by the user, share the count of times the number was provided earlier by the user.


# hash with key "random_numbers_key" and value is empty array
random_numbers_hash = {}
random_array = Array.new # array for random numbers 
array_user_inputs = Array.new # array for user inputs

# times loop to generate 5 random numbers between 12 and 21, both inclusive
5.times do |i|
  rand_number = rand(12..21)
  random_array[i] = rand_number
end

# add key "random_numbers" and value "random_array" to hash
random_numbers_hash[ :random_numbers] = random_array

puts random_numbers_hash
puts ""

# times loop to get user input numbers  between 12 and 21, both inclusive and add them to array
puts "Please provide five integer values between 12 and 21, both inclusive:"
puts ""
5.times do |i|
  puts "What's number #{i + 1}?"
  input = gets
  input = input.to_i
  array_user_inputs.push(input)
end

# add key "user_input" and value "array_user_inputs" to hash
random_numbers_hash[ :user_input] = array_user_inputs

puts ""

puts random_numbers_hash

i = 0
array_count_random = Array.new # create an array to keep random value if it meets in random generated array
array_user_provide = Array.new # create an array to keep value user supply if it meets in user input array
3.times do # ask user 3 times to supply 3 numbers
  puts "Give me a number you want information about:"
  gave_number = gets
  gave_number = gave_number.to_i
  5.times do |i| # 5 times loop to compare number user provided with each value in a hash
    if gave_number == random_numbers_hash[ :random_numbers][i]
      array_count_random.push(gave_number) # add gave number to array if it equal value from hash (key :random_numbers) to count the length of array
    end
    if gave_number == random_numbers_hash[ :user_input][i]
      array_user_provide.push(gave_number) # add gave number to array if it equal value from hash (key :user_input) to count the length of array
    end
    i += 1
  end
  puts "#{array_count_random}"
  puts "#{array_user_provide}"
  # print the count of times the number was generated by the program and provided by user
   puts "Using hash:"
   if array_count_random.length > 0
     puts "The number, #{gave_number} shows up #{array_count_random.length} time(s) in the randomly generated numbers."
   else 
     puts "The number, #{gave_number} did not show in the randomly generated numbers."
   end
   if array_user_provide.length > 0
    puts "The number, #{gave_number} was provided #{array_user_provide.length} time(s) by the user earlier."
   else
    puts "The number, #{gave_number} was not provided by the user earlier."
   end
  # create the same arrays to set to zero the length of arrays for next loop
  array_count_random = Array.new
  array_user_provide = Array.new
end